### PR TITLE
DTLS sliding window improvements

### PR DESCRIPTION
**Pull request by nmav**
This set of patches improves the DTLS sliding window handling.

### CODE REVIEW

**Comment by fridex** [comment]
> That is handle the case where the sliding window is uninitialized
and a packet with sequence number of zero is received.

I am not sure here, when this can occur?

**Comment by nmav** [comment]
>>    dtls-sw: handle separately the case of uninitialized window
>>    That is handle the case where the sliding window is uninitialized
>>    and a packet with sequence number of zero is received.
> I am not sure here, when this can occur?

On the first received packet on an epoch, which will have seq nr 0 and will be rejected as only values > start are accepted.  I believe it has not been noticed with af_ktls because you don't see the first packet at all (it is the finished message). I found that issue when trying this implementation on gnutls.

**Comment by fridex** [comment]
Ah, now I see.

Should we merge it here? I would like to keep the implementation minimal and this (if I understand correctly) shouldn't occur in AF_KTLS since we will receive only application data - this should be handled in user space during the handshake?

Nevertheless using fixed size values in dtls_window is meaningful in my opinion.

**Comment by nmav** [comment]
> Should we merge it here? I would like to keep the implementation minimal and this (if I understand correctly) shouldn't occur in AF_KTLS since we will receive only application data - this should be handled in user space during the handshake?

I cannot think of any case where that will be needed. It would be nice to have a comment about this limitation though.

**Comment by nmav** [comment]
I'll update the patches to remove that.

**Pull request merged**
