### PR TITLE
Fix crash sock_register fails

### PR DESCRIPTION
**Pull request by fridex**
fixes: #31

### CODE REVIEW

**Comment by fridex** [comment]
@djwatson Does the problem still persist after this patch?

Thanks!

**Comment by djwatson** [comment]
I haven't had a chance to test this, but it still looks like 'sock_unregister(PF_KTLS);' is called unconditionally in exit, which was the issue, even if we didn't call sock_register, or sock_register failed.  Need some sort of check in tls_exit

**Comment by fridex** [comment]
IMHO tls_exit shouldn't be called, since there will an error in tls_init (the error was not propagated correctly), but worth to check it out.

**Comment by fridex** [comment]
I tried to simulate sock_register() fail by trying to register (already registered) PF_INET in AF_KTLS. I tried proto_register() fail as well.  In both cases tls_exit() was not called. If you don't have any objections, I will merge this.

**Comment by djwatson** [comment]
go for it

**Pull request merged**
